books/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

   root 'welcome#index'

   resources :documents

end

books/app/models/document.rb
class Document < ActiveRecord::Base
	validates :title, presence: true, length: {minimum: 5}
	
end

books/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

books/app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
	
	def new		
		@document = Document.new
	end

	def index
		
		@documents = Document.paginate(:page => params[:page], :per_page => 3)
	end

	def create
		@document = Document.new(document_params)
			
		if @document.save
			redirect_to @document	
		else
			render 'new'
		end			
	end

	def show
		@document =  Document.find(params[:id])

	end

	def edit
		@document = Document.find(params[:id])
	end

	def update
		@document = Document.find(params[:id])

		if @document.update(document_params)
			redirect_to @document
		else
			render 'edit'
		end

	end

	def destroy
		@document = Document.find(params[:id])
		@document.destroy

		redirect_to documents_path
	end

	private
		def document_params
			params.require(:document).permit(:title, :content)
		end

end

books/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

books/app/helpers/application_helper.rb
module ApplicationHelper
end

books/app/helpers/documents_helper.rb
module DocumentsHelper
end

books/app/helpers/welcome_helper.rb
module WelcomeHelper
end

books/app/views/documents/_form.html.erb
<div class="row">
	<div class="col-md-6">
		<%= form_for @document, role:"form" do |f| %>

		<% if @document.errors.any? %>
	  <div id="error_explanation">
	  	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	    <h2><%= pluralize(@document.errors.count, "error") %> prohibited
	      this document from being saved:</h2>
	    <ul>
	    <% @document.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
	  <% end %>
		
		  <div class="form-group">
		    <%= f.label :title %>
		    <%= f.text_field :title, class:"form-control", placeholder:"document title" %>
		  </div>
		  <div class="form-group">
		    <%= f.label :content %>
		    <%= f.text_area :content, class:"form-control txt", placeholder:"document content", rows:"10" %>
		  </div>

	 	  <script type="text/javascript">
			  $(document).ready(function(){

			    $('.txt').each(function(i, elem) {
			      $(elem).wysihtml5();
			    });

			  })
			</script>
		  
		  
		  <%= f.submit :submit, class:"btn btn-success" %>
			<a href="<%= documents_path %>" class="btn btn-info"><%= fa_icon "angle-left" %> Back</a>
		<% end %>
	</div>
	<div class="col-md-6">
		Excepteur sint obcaecat cupiditat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Excepteur sint obcaecat cupiditat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
	</div>
</div>

books/app/views/documents/edit.html.erb
<h1> <%= fa_icon "edit" %> Edit Document</h1>
<%= render 'form' %>

books/app/views/documents/index.html.erb
<h1>
  <%= fa_icon "book" %> Documents Available
  <a href="<%= new_document_path %>" class="btn btn-success pull-right"> Add Document</a>
</h1>
<table class="table table-striped">
  <th>Title</th>
  <th>Content</th>
  <th>Action</th>
  <%  @documents.each do |d| %>
  	<tr>
  		<td><%= d.title %></td>
  		<td><%= truncate(d.content, :length => 80) %></td>
  		<td>
  			<%= link_to 'Show', document_path(d) %> | 
        <%= link_to 'Edit', edit_document_path(d) %> |
        <%= link_to 'Destroy', document_path(d),
                    method: :delete, data: { confirm: 'Are you sure?' } %>
  		</td>
  	</tr>

  <% end %>

</table>
<%= will_paginate @documents %>

books/app/views/documents/new.html.erb
<h1>  <%= fa_icon "book" %> Add new document</h1>
<%= render 'form' %>

books/app/views/documents/show.html.erb
<h1><%= @document.title %></h1>
<p><%= @document.content %></p>
<p>
	
	<a href="<%= documents_path %>" class="btn btn-success"> <%= fa_icon "angle-left" %> Back </a>
	<a href="<%= edit_document_path %>" class="btn btn-info"> <%= fa_icon "edit" %> Edit </a>
</p>

books/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fpkkl</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

<!-- Latest compiled and minified JavaScript -->

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
<%= yield %>
</div>
</body>
</html>

books/app/views/welcome/index.html.erb
<div id="main">
  <div class="row">
    <div class="col-md-6" id="head">
      <h1>FPKKL</h1>
    </div>
    <div class="col-md-6">
      <h2>Forum Perpustakaan Khusus Kementrian Lembaga</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12" id="navigate">
      <a href="<%= new_document_path %>" class="btn btn-success"> Add Document</a>
      <a href="<%= documents_path %>" class="btn btn-info"> List Document</a>
    </div>
  </div>
</div>